---
- hosts: routeros
  connection: local
  gather_facts: false
  tasks:
   - name: Display resource statistics (routeros)
     routeros_command:
      commands:
       - /log print
     register: print_out
   - name: output to screen
     debug:
       var: print_out
