---

- hosts: routeros
  connection: local
  vars:
    schedule: '*/15 * * * *'
    cron_user: tac
    logfile: /myansible/ansible-pull.log
    workdir: /myansible/local
    repo_url: git://github.com:stqb-fsd/anspull.git
  tasks:
   - name: Display resource statistics (routeros)
     routeros_command:
      commands:
       - /log print
     register: print_out
   - name: output to screen
     debug:
       var: print_out
